name: web_funnel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.1
  auto_route: ^9.2.2
  get_it: ^8.0.0
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  easy_localization_generator: ^0.3.2
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/localization/

flutter_gen:
  output: lib/core/gen
  integrations:
    flutter_svg: true
    lottie: true
